---
title: "DM model shiny prototype 2"
output: html_document
date: "2024-08-23"
---

Second prototype of DM model shiny app
- loads in fitted models (Thomas, OLR) from file rather than fitting within app
- plots mature edge seed trees & mature edge DM infection (doesn't model spread to regen trees)

Load packages
```{r}
rm(list=ls(all=TRUE))
library(shiny)
library(shinycssloaders)
library(Cairo)

library(data.table)
library(tidyverse)
library(terra)
library(ggplot2)
library(raster)
library(tidyterra)
library(spatstat)
library(openxlsx)
library(sf)
library(MASS)
library(Rdice)
library(here)
here()
setwd(here("./stand model/dm_model_demo-main"))
```

load data
```{r}
# load stem density data (stratified by species and crown class) for regenerated and mature plots
regen_density_sum <- read.csv("regen stem density canopy class.csv") %>% setDT()

mature_density_sum <- read.csv("mature stem density canopy class.csv") %>% setDT()

# load Variable retention shapefile
regen_base <- vect("selected variable retention cutblocks.shp")

# load fitted models
load("thomas_model.rda")
load("olr_model.rda")

```


Import variable retention shapefile
```{r}
## take first cutblock
## regen tree cutblock (spatvector)
regen_base_1 <- regen_base[1]

```

Shiny app - user interface
```{r}
ui <- fluidPage(
  
  sidebarLayout(
    sidebarPanel(
      numericInput("mat_width", label = "Width of mature tree edge (m)", min = 1, value = 20),
      sliderInput("intensity", label = "Adjust mature edge infection intensity",
                  min = 0.25, max = 5,
                  value = 1, step = 0.25),
      actionButton("run_mod", "Run model"),
      span(htmlOutput("time"), style = "color:red")
    ),
    mainPanel(
      h4("Brush and double-click to zoom"),
      fluidRow(
        column(width = 10, class = "well",
               textOutput("plot1_title"),
               plotOutput("plot1",
                          dblclick = "plot1_dblclick",
                          brush = brushOpts(
                            id = "plot_brush",
                            resetOnNew = TRUE))
        ),
        column(width = 10, class = "well",
               textOutput("plot2_title"),
               plotOutput("plot2",
                          dblclick = "plot2_dblclick",
                          brush = brushOpts(
                            id = "plot_brush",
                            resetOnNew = TRUE))
        )
      )
    )
  )
)
```

Shiny app - server
```{r}

server <- function(input, output){
  
  observeEvent(input$run_mod, {
    
    showPageSpinner(type = 1)
    Sys.sleep(1)
    
    start_time <- Sys.time()
    
    # user input values
    mat_width <- input$mat_width
    intensity <- input$intensity
    
    # mature tree edge (spatvector)
    mature_vect <- regen_base_1 %>%
      buffer(width = mat_width) %>%
      erase(regen_base_1)
    
    #-------------------------------------------------|
    # 1. convert cutblock shapefiles to raster format
    #-------------------------------------------------|
    shp_to_rast <- function(regen_edge_vect){
  
      # 1. create raster with extent of cutblock + mature edge
      vect_buffer <- buffer(regen_edge_vect, mat_width)
      
      raster <- rast(xmin = round(ext(vect_buffer)[1], 0),
                     xmax = round(ext(vect_buffer)[2], 0),
                     ymin = round(ext(vect_buffer)[3], 0),
                     ymax = round(ext(vect_buffer)[4], 0),
                     res = c(1, 1))
      
      crs(raster) <- "EPSG:3005"
      
      raster$cell_num <- 1:ncell(raster)
      crop_rast <- crop(raster, vect_buffer, mask = TRUE)
      
      # 2. create regen raster
      regen_rast <- crop(crop_rast, regen_edge_vect, mask = TRUE)
      
      # 3. create mature raster
      base_rast_df <- as.data.frame(crop_rast, xy = TRUE) %>%
        setDT()
      
      regen_rast_df <- as.data.frame(regen_rast, xy = TRUE) %>%
        mutate(tree_type = "regen") %>%
        setDT()
      
      mature_rast <- base_rast_df[!(base_rast_df$cell_num %in% regen_rast_df$cell_num)] %>%
        rast()
      
      # 4. combine regen and mature rasters
      mature_rast_df <- as.data.frame(mature_rast, xy = TRUE) %>%
        mutate(tree_type = "mature") %>%
        setDT()
      
      all_rast <- rbind(regen_rast_df, mature_rast_df)
      
      return(all_rast)
    }
    
    ## rasterized regen and mature components of cutblock
    rast_trees_dt <- shp_to_rast(regen_base_1)
    
    #-------------------------------------------------------------------------------|
    # 2. Load cluster process model to predict point pattern of "seed trees" (where dmr == 6)
    # model fitted to Shaw et al. (2005) data
    #-------------------------------------------------------------------------------|
    # 1. transform mature edge of variable retention cutblock to owin format for modelling
    mature_edge_win <- mature_vect %>%
      st_as_sf(crs = "EPSG:3005") %>%
      as.owin()
    
    # 2. load in Thomas cluster model & simulate point process
    thomas_sim <- rThomas(
      kappa = thomas_model$modelpar["kappa"] * intensity,
      scale = thomas_model$modelpar["sigma"],
      mu = thomas_model$modelpar["mu"],
      win = mature_edge_win
    )
    
    # 3. convert Thomas cluster points to data frame
    mature_seeds_dt <- as.data.frame.ppp(thomas_sim)
    rownames(mature_seeds_dt) <- NULL
    mature_seeds_dt %<>%
      mutate(dmr = 6,
             spp = "Hw") %>%
      setDT()
    
    #--------------------------------------------------------------------|
    # 3. Sample Hw & non-Hw mature trees at set stem density
    #--------------------------------------------------------------------|
    # 1. Rasterize Thomas point cluster process simulation for mature edge
    
    rasterize_points <- function(regen_edge_vect, mature_seeds_dt){
      
      vect_buffer <- buffer(regen_edge_vect, mat_width)
      raster <- rast(xmin = round(ext(vect_buffer)[1], 0),
                       xmax = round(ext(vect_buffer)[2], 0),
                       ymin = round(ext(vect_buffer)[3], 0),
                       ymax = round(ext(vect_buffer)[4], 0),
                       res = c(1, 1))
      crs(raster) <- "EPSG:3005"
      raster$cell_num <- 1:ncell(raster)
      
      mature_seeds_vect <- vect(mature_seeds_dt, geom = c("x", "y"), crs = "EPSG:3005", keepgeom = FALSE)
      
      mature_seeds_rast <- rasterize(mature_seeds_vect, raster)
      mature_seeds_dt <- as.data.frame(mature_seeds_rast, xy = TRUE) %>%
        mutate(row_num = row_number(),
               key = paste0(x, "_", y)) %>%
        mutate(dmr = 6,
              tree_type = "mature",
              species = "Hw") %>%
        dplyr::select(x, y, tree_type, key, dmr, species) %>%
        setDT()
      
      return(mature_seeds_dt)
    }
    
    # 2. Sample Hw & non-Hw trees from remaining mature raster
    
    sample_mature <- function(rast_trees_dt, mature_seeds_dt, mature_density_sum){
      
      ## 1. format mature edge raster to dt
      setDT(rast_trees_dt)
      mature_trees_dt <- rast_trees_dt[tree_type == "mature",][,key := paste0(x, "_", y)] 
      
      ## 2. take out mature seeds (already sampled Hw, mature trees)
      mature_dt <- mature_trees_dt[!(mature_trees_dt$key %in% mature_seeds_dt$key)]
      
      ## 3. calculate number of Hw trees left to sample
      num_hw_sampled <- nrow(mature_trees_dt) - nrow(mature_dt)
      hw_mature_num <- round(sum(mature_density_sum[species == "Hw"]$stem_den_m2) * nrow(mature_trees_dt)) - num_hw_sampled
      
      ## 4. calculate number of non-Hw trees to sample
      non_hw_mature_num <- round(sum(mature_density_sum[species == "non-Hw"]$stem_den_m2) * nrow(mature_trees_dt))
      
      ## 5. sample for Hw trees in mature edge
      samp_mature_hw <- mature_dt[sample(nrow(mature_dt), hw_mature_num),] %>%
        mutate(dmr = 0,
               tree_type = "mature",
               species = "Hw") %>%
        setDT()
      
      ## 6. sample for non-Hw trees in mature edge
      ## take out sampled trees first
      mature_non_hw <- mature_dt[!(mature_dt$key %in% samp_mature_hw$key)]
      ## sample
      samp_mature_non_hw <- mature_non_hw[sample(nrow(mature_non_hw), non_hw_mature_num),] %>%
        mutate(dmr = 0,
               tree_type = "mature",
               species = "non-Hw") %>%
        setDT()
      
      ## combine sampled Hw and non-Hw trees
      mature_non_seeds_dt <- rbind(samp_mature_hw[,.(x, y, tree_type, key, dmr, species)],
                                   samp_mature_non_hw[,.(x, y, tree_type, key, dmr, species)])
      
      return(mature_non_seeds_dt)
    }
    
    # 3. Combine sampled seed and non-seed trees
    mature_seeds_dt <- rasterize_points(regen_base_1, mature_seeds_dt)
    mature_non_seeds_dt <- sample_mature(rast_trees_dt, mature_seeds_dt, mature_density_sum)
    
    mature_sample <- rbind(mature_seeds_dt, mature_non_seeds_dt)
    
    #--------------------------------------------------------------|
    # 4. Load fitted ordinal logistic regression model
    # model fitted to Shaw et al. (2005) data
    #--------------------------------------------------------------|
    # 1. Define functions for calculating euclidean distance and distance from tree to nearest seed tree (dmr == 6)
    euclidean <- function(x1, y1, x2, y2){
      dist <- sqrt((x1 - x2)^2 + (y1 - y2)^2)
      return(dist)
    }
    
    dist_to_seed <- function(inf_cluster){
      
      non_seeds <- inf_cluster[dmr < 6]
      seeds <- inf_cluster[dmr == 6]
      
      for (ns in 1:nrow(non_seeds)){
        current_tree <- non_seeds[ns]
        dist_to_seeds <- seeds %>%
          mutate(dist_to_seed = euclidean(current_tree$x, current_tree$y,
                                          x, y)) %>%
          arrange(dist_to_seed) %>%
          dplyr::filter(row_number() == 1) %>%
          mutate(target_ID = ns,
                 target_x = current_tree$x, 
                 target_y = current_tree$y,
                 target_dmr = current_tree$dmr,
                 seed_dmr = dmr) %>%
          dplyr::select(target_ID, target_x, target_y, target_dmr, seed_dmr, dist_to_seed) %>%
          setDT()
        
        if (ns == 1){
          final_result <- dist_to_seeds
        } else {
          final_result <- rbind(final_result, dist_to_seeds)
        }
      }
      return(final_result) 
    }
    
    #--------------------------------------------------------------|
    # 5. Predict infection spread in mature edge using fitted OLR model 
    #--------------------------------------------------------------|
    
    # 1. calculate euclidean distance of each tree to the nearest seed tree
    dist_mature <- mature_sample[species == "Hw", ] %>% # only infect Hw trees
      dist_to_seed()
    
    # 2. Predict probability of infection for each tree
    pred_mature <- predict(olr_model, dist_mature, type = "p")
    ## clean & format results
    pred_mature_dt <- cbind(dist_mature[,.(target_x, target_y, target_dmr, dist_to_seed)],
                            pred_mature) %>%
      mutate(key = paste0(target_x, "_", target_y)) %>%
      pivot_longer(cols = `0`:`5`,
                   names_to = "possible_dmr",
                   values_to = "probability") %>%
      setDT()
    
    # 3. Predict dmr from probability
    pred_mature_final <- pred_mature_dt %>%
      group_by(key) %>%
      mutate(dmr_assigned = dice.roll(faces = 6, dice = 1, rolls = 1,
                                      weights = c(probability))$results$values - 1) %>%
      dplyr::select(key, dist_to_seed, dmr_assigned, target_x, target_y) %>%
      mutate(dmr_assigned = as.numeric(dmr_assigned)) %>%
      rename("x" = "target_x",
             "y" = "target_y") %>%
      distinct() %>%
      setDT()
    
    # 4. Join predicted dmr for Hw trees with all mature trees
    inf_mature_sample <- merge(mature_sample, pred_mature_final[, .(key, dmr_assigned)], by = "key",
                               all.x = TRUE) %>%
      setDT()
    
    inf_mature_sample <- inf_mature_sample[, dmr_final := ifelse(is.na(dmr_assigned), dmr,
                                                                 ifelse(dmr == 0, dmr_assigned, dmr))] %>%
      dplyr::select(!c(dmr, dmr_assigned)) %>%
      rename("dmr" = "dmr_final")
    
    #--------------------------------------------------------------|
    # 6. Sample Hw & non-Hw regen trees at set stem density
    #--------------------------------------------------------------|
    sample_regen <- function(rast_trees_dt, regen_density_sum){
      
      ## 1. format regen raster to dt
      setDT(rast_trees_dt)
      regen_trees_dt <- rast_trees_dt[tree_type == "regen",]
      
      ## 2. calculate number of regen trees to sample for
      ## Hw
      hw_regen_num <- round(sum(regen_density_sum[species == "Hw"]$stem_den_m2) * nrow(regen_trees_dt))
      ## non-Hw
      non_hw_regen_num <- round(sum(regen_density_sum[species == "non-Hw"]$stem_den_m2) * nrow(regen_trees_dt))
      ## total
      samp_num <- hw_regen_num + non_hw_regen_num
      
      ## 3. sample for regen trees & assign as Hw or non-Hw
      samp_regen <- regen_trees_dt[sample(nrow(regen_trees_dt), samp_num),] %>%
        mutate(species = sample(c(rep("Hw", hw_regen_num),
                                  rep("non-Hw", non_hw_regen_num)),
                                samp_num)) %>%
        setDT()
      
      return(samp_regen)
    }
    
    regen_sample <- sample_regen(rast_trees_dt, regen_density_sum)
    regen_sample <- regen_sample[, dmr := 0]
    
    #--------------------------------------------------------------|
    # 7. Join mature and regen trees together
    #--------------------------------------------------------------|    
    all_trees_sample <- rbind(inf_mature_sample[, .(x, y, tree_type, species, dmr)],
                              regen_sample[, .(x, y, tree_type, species, dmr)])
    
    all_seeds_sample <- rbind(mature_sample[,.(x, y, tree_type, species, dmr)],
                              regen_sample[, .(x, y, tree_type, species, dmr)])
    
    #-------------------------------------------------|
    # generate + display DM model results
    #-------------------------------------------------|
    
    # zoomable plot for infection spread results ------
    ranges <- reactiveValues(x = NULL, y = NULL)
    
    # render plot 1
    output$plot1 <- renderPlot({
      ggplot() +
        geom_tile(data = rast_trees_dt, aes(x = x, y = y, fill = tree_type)) +
        scale_fill_manual(values = c(regen = "seashell", mature = "burlywood1")) +
        ggnewscale::new_scale_fill() +
        geom_point(data = all_trees_sample, aes(x = x, y = y, color = dmr), size = 0.2) +
        geom_point(data = all_trees_sample[dmr > 0], aes(x = x, y = y, color = dmr), size = 0.5) +
        scale_color_gradient(low = "seagreen3", high = "red") +
        geom_spatvector(data = mature_vect, fill = NA, colour = "black", lwd = 0.7) +
        coord_sf(xlim = ranges$x, ylim = ranges$y, expand = FALSE)
    })
    
    output$plot1_title <- renderText({
      "Dwarf Mistletoe infection in mature edge"
    })
    
    # render plot 2
    # zoomable plot for infection seeds -------------
    output$plot2 <- renderPlot({
      # ggplot() +
      #   geom_point(data = all_seeds_sample, aes(x = x, y = y, color = dmr), size = 0.5) +
      #   scale_color_gradient(low = "seagreen2", high = "red") +
      #   geom_spatvector(data = mature_vect, fill = NA, colour = "black", lwd = 0.7) +
      #   coord_sf(xlim = ranges$x, ylim = ranges$y, expand = FALSE)
      ggplot() +
        geom_tile(data = rast_trees_dt, aes(x = x, y = y, fill = tree_type)) +
        scale_fill_manual(values = c(regen = "seashell", mature = "burlywood1")) +
        ggnewscale::new_scale_fill() +
        geom_point(data = all_seeds_sample, aes(x = x, y = y, color = dmr), size = 0.2) +
        geom_point(data = all_seeds_sample[dmr == 6],
                   aes(x = x, y = y),
                   color = "red",
                   size = 0.5) +
        scale_color_gradient(low = "seagreen3", high = "red") +
        geom_spatvector(data = mature_vect, fill = NA, colour = "black", lwd = 0.7)+
        coord_sf(xlim = ranges$x, ylim = ranges$y, expand = FALSE)
    })
    
    output$plot2_title <- renderText({
      "Dwarf Mistletoe seed trees in mature edge"
    })
    
    # check if there's a brush on the plot when a double-click happens ---------
    # if there's a brush, zoom to brush bounds
    # if no brush, reset the zoom
    observeEvent(input$plot1_dblclick, {
      brush <- input$plot_brush
      if (!is.null(brush)) {
        ranges$x <- c(brush$xmin, brush$xmax)
        ranges$y <- c(brush$ymin, brush$ymax)
      } else {
        ranges$x <- NULL
        ranges$y <- NULL
      }
    })
    
    observeEvent(input$plot2_dblclick, {
      brush <- input$plot_brush
      if (!is.null(brush)) {
        ranges$x <- c(brush$xmin, brush$xmax)
        ranges$y <- c(brush$ymin, brush$ymax)
      } else {
        ranges$x <- NULL
        ranges$y <- NULL
      }
    })
    
    end_time <- Sys.time()
    run_time <- round(difftime(end_time, start_time, units = "mins"), 3)

    output$time <- renderText({
      paste0("Model runtime: ", run_time, " mins")
    })
    
    hidePageSpinner()
    
  })
  
}

```

Run Shiny app
```{r}
shinyApp(ui, server)

```

